# Generated by Django 3.1.2 on 2020-10-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20201022_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='url',
        ),
    ]
