# Generated by Django 3.1.2 on 2020-10-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20201022_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='politics',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sports',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
