# Generated by Django 3.1.2 on 2020-10-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_auto_20201024_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='url',
        ),
    ]
